### ISSUE TITLE
Support for es6 module in karma

### ISSUE THREAD

**Issue by janbaer** [6to5/karma-6to5-preprocessor#3]
I'm trying to use the karma-6to5 preprocessor to export a module with the es6 syntax and the import it in a jasmine test, but it doesn't works.

This is my exported function.

export function bar() {
  return 'bar';
}
I imported it in my test, but when I try to execute my test I get the following error on the console

ReferenceError: Can't find variable: exports
at module1.es5.js:3
"use strict"
nexports.bar = bar;

function bar() {
  return "bar"
}

module1.js contains the exported function. Where is here the problem?

**Comment by sebmck** [comment]
Closed via 6to5/6to5#650

**Comment by luckygirlalisa** [comment]
Got 404 when visit babel/babel#650 (https://github.com/babel/babel/issues/650).

**Comment by shuhei** [comment]
babel/babel's issues moved to https://phabricator.babeljs.io/

Not sure whether we can find the issue on phabricator from the original github issue ID.

**Comment by danbruegge** [comment]
https://phabricator.babeljs.io/T650
