### ISSUE TITLE
With to5Options.moduleIds: true module names include whole path

### ISSUE THREAD

**Issue by johlrich** [6to5/karma-6to5-preprocessor#5]
With to5Options.moduleIds: true module names are including the entire path. I tried setting the sourceRoot, but then the path was duplicated before the desired module portion.

The only way I was able to get just the module portion was to add filenameRelative to the per file options and assign it a function to strip the initial path. I feel like I'm missing something simple over this being a bug. Thoughts?

Not sure if this matters, but I am on windows.

**Comment by sebmck** [comment]
Actually a bug with 6to5, can you report it on the [main repo](http://github.com/6to5/6to5)? Thanks!

**Comment by sebmck** [comment]
Actually, it's not *really* a bug. Can you provide the `sourceRoot` you're using?

**Comment by johlrich** [comment]
With no option set i get the full path like `C:/Dev/bitbucket/ng-devenv/workform/workform.spec`

With option set to `process.cwd()` (which returns `C:/Dev/bitbucket/ng-devenv`) i get `C:/Dev/bitbucket/ng-devenv/C:/Dev/bitbucket/ng-devenv/workform/workform.spec`

**Comment by johlrich** [comment]
You're too fast, commits before I can reply. I'll try this out and report back

**Comment by sebmck** [comment]
@johlrich It'd be because internally the `filename` is normalised to unix path separators. So `C:\foo\test.js` is turned into `c:/foo/test.js`, this just makes path handling a lot more easier.

You'd be passing it a `sourceRoot` that uses `\` instead of `/`. I just pushed a patch that will also normalise `sourceRoot` in the same way.

**Comment by johlrich** [comment]
Behavior with the sourceRoot set to process.cwd() now sets the moduleid to `C:/Dev/bitbucket/ng-devenv//workform/workform.spec`

Haven't dug around yet to see what may be off

**Comment by sebmck** [comment]
Huh, weird. It possibly has something to do with Windows path separators. Thought that might have fixed it. Can you reopen this in the [main repo](https://github.com/6to5/6to5.github.io)? I'll have a look in the morning.
